#num=int(input("give the value of num:"))
#print("you entered:",num,sep="")
#n=int(input(""))
#print("value of pi:",n,sep="")
#a=input()
#x,y,z=a.split(" ")
#sum=int(x)+int(y)+int(z)
#print(sum)
#a=input("enter your name and age")
#name,age=a.split(",")
#b=int(age)
#print("name:",name,"age:",b,sep="")
n=int(input("enter n:"))
print( "countdown:5 4 3 2 1",end="Blast off!")